#!/bin/bash

. common.sh

# gen_server_config(S_IP, S_PORT, S_NAME, S_FILE)
gen_server_config() {
    if ( (($# < 4)) ); then
        fatal 'Not enough parameters'
    fi

    S_IP=$1
    S_PORT=$2
    S_NAME=$3
    S_FILE=$4

    if [ -f $S_FILE ]; then
        fatal "$S_FILE already exists. Not overwriting."
    else
        touch $S_FILE
    fi

    S_PRIVKEY=$(wg genkey)
    S_PUBKEY=$(echo $S_PRIVKEY | wg pubkey)

    echo -e "# Auto-Generated by script\n\n#$S_NAME\n[Interface]\nAddress=$S_IP/24\nPostUp=iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE\nPostDown= iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE\nListenPort=$S_PORT\nPrivateKey=$S_PRIVKEY\n#PublicKey=$S_PUBKEY" > $S_FILE
    
    info "$S_NAME configuration successfully written to $S_FILE"

    exit 0
}

while getopts ":a:p:n:f:" arg; do
  case $arg in
    a) S_IP=$OPTARG;;
    p) S_PORT=$OPTARG;;
    n) S_NAME=$OPTARG;;
    f) S_FILE=$OPTARG;;
  esac
done

gen_server_config $S_IP $S_PORT $S_NAME $S_FILE